name: Scrolls
version: 2.1
description: This is scrolls done right.
authors: ['Knaxel (Cole Philipp)', 'ame94']
main: scrolls.ScrollsPlugin

commands:
    scrolls:
        description: The base Scrolls Command
        aliases: [scroll,sc,scr]
        permission: scrolls.command
        usage: Please use '/scrolls help' if you dont know how to use the command...
